CREATE TABLE HELPTICKET(
    HELPTICKETID INT NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY,
    "USERID" INT NOT NULL,
    "DETAILS" VARCHAR(1000),
    "RESPONSE" VARCHAR (1000),
    "CATEGORY" VARCHAR (50),
    "SENT" DATE NOT NULL,
    "STAFFID" INT,
    "ASSIGNED" VARCHAR (10),
    "COMPLETED" VARCHAR (10)
);