CREATE TABLE ENQUIRY (
ENQUIRYID INT NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1, INCREMENT BY 1),
"USERIDSENDER" INT,
"USERIDRECEIEVER" INT,
"SENTMESSAGE"VARCHAR(1000),
"RECEIVEDMESSAGE" VARCHAR(1000)
);