CREATE TABLE ROLE(
    ROLEID VARCHAR NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY
    "ROLENAME" VARCHAR(20),
    PRIMARY KEY (ROLEID),
    FOREIGN KEY (USERID) REFERENCES USER_ACCOUNT
);

CREATE TABLE USER_ACCOUNT(
    USERID VARCHAR NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY
    "FNAME" VARCHAR(50),
    "LNAME" VARCHAR(50),
    "ADDRESS" VARCHAR(100),
    "DATEOFBIRTH" VARCHAR(10),
    "EMAILADDRESS" VARCHAR(100),
    "CONTACTNUMBER" INTEGER
    "PASSWORD" VARCHAR(50),
    PRIMARY KEY (USERID),
    FOREIGN KEY (ROLEID) REFERENCES ROLE
);

CREATE TABLE AUCTION_ITEM (
    ITEMID VARCHAR NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY
    "PROPERTYID" VARCHAR NOT NULL,
    "STAFFUSERID" VARCHAR NOT NULL,
    "SELLERID" VARCHAR NOT NULL,
    "SOLDTO" VARCHAR,
    "KEYWORDID" VARCHAR NOT NULL,
    "PURCHASEID" VARCHAR,
    "SOLDFOR" INT,
    "DATEVERIFIED" DATE,
    "STARTDATE" DATE NOT NULL,
    "STARTTIME" TIME NOT NULL,
    "ENDDATE" DATE NOT NULL,
    "ENDTIME" TIME NOT NULL,
    "RESERVEPRICE" INT NOT NULL,
    "STARTINGPRICE" INT NOT NULL,
    "STATUS" VARCHAR NOT NULL,
    PRIMARY KEY (ITEMID),
    FOREIGN KEY (PROPERTYID) REFERENCES 
    FOREIGN KEY (STAFFUSERID) REFERENCES 
    FOREIGN KEY (SELLERID) REFERENCES 
    FOREIGN KEY (SOLDTO) REFERENCES 
    FOREIGN KEY (KEYWORDID) REFERENCES 
    FOREIGN KEY (PURCHASEID) REFERENCES
)