CREATE TABLE OPEN_DAY_BOOKING (
"BOOKINGID" INT NOT NULL
GENERATED ALWAYS AS IDENTITY
"STAFFID" INT NOT NULL
"USERID" INT,
"PROPERTYID" INT NOT NULL,
"DATE" DATE NOT NULL,
"TIME" TIME NOT NULL,
PRIMARY KEY (BOOKINGID),
FOREIGN KEY (STAFFID) REFERENCES USER_ACCOUNT,
FOREIGN KEY (USERID) REFERENCES USER_ACCOUNT
FOREIGN KEY (PROPERTYID) REFERENCES PROPERTY
);