CREATE TABLE HELPTICKET(
    HELPTICKETID INT NOT NULL
    GENERATED ALWAYS AS IDENTITY,
    "USERID" INT NOT NULL,
    "DETAILS" VARCHAR(200),
    "CATEGORY" VARCHAR (50),
    "SENT" DATE NOT NULL,
    "STAFFID" INT,
    "ASSIGNED" VARCHAR (10),
    "COMPLETED" VARCHAR (10)
);