CREATE TABLE OPEN_DAY_BOOKING (
    "BOOKINGID" INT NOT NULL
    GENERATED ALWAYS AS IDENTIY,
    "STAFFID" INT NOT NULL,
    "USERID" INT,
    "PROPERTYID" INT NOT NULL,
    "DATE" DATE NOT NULL,
    "STARTTIME" TIME NOT NULL,
    "ENDTIME" TIME NOT NULL,
    "STATUS" INT NOT NULL,
    PRIMARY KEY (BOOKINGID),
    FOREIGN KEY (STAFFID) REFERENCES USER_ACCOUNT,
    FOREIGN KEY (USERID) REFERENCES USER_ACCOUNT,
    FOREIGN KEY (PROPERTYID) REFERENCES PROPERTY
);