CREATE TABLE ROLE(
    ROLEID VARCHAR NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY
    "ROLENAME" VARCHAR(20),
    PRIMARY KEY (ROLEID),
    FOREIGN KEY (USERID) REFERENCES USER_ACCOUNT
);

CREATE TABLE USER_ACCOUNT(
    USERID VARCHAR NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY
    "FNAME" VARCHAR(50),
    "LNAME" VARCHAR(50),
    "ADDRESS" VARCHAR(100),
    "DATEOFBIRTH" VARCHAR(10),
    "EMAILADDRESS" VARCHAR(100),
    "CONTACTNUMBER" INTEGER
    "PASSWORD" VARCHAR(50),
    PRIMARY KEY (USERID),
    FOREIGN KEY (ROLEID) REFERENCES ROLE
);