CREATE TABLE STAMP_DUTY(
    PRICECAT INT,
    VARIABLEPRICE INT,
    VARIABLEINCREASE DOUBLE,
    DUITABLEVALUE INT
);

INSERT INTO STAMP_DUTY (PRICECAT, VARIABLEPRICE, VARIABLEINCREASE, DUITABLEVALUE)
VALUES

