CREATE TABLE PROPERTY(
    PROPERTYID INT NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1, INCREMENT BY 1),
    "SUBURB" VARCHAR(50),
    "ADDRESS" VARCHAR(100),
    "POSTCODE" VARCHAR(10),
    "STATE" VARCHAR(10),
    "DESCR" VARCHAR(100),
    "BATHROOM" INT,
    "BEDROOM" INT,
    "GARAGE" INT,
    "USERID" INT,
    "STATUS" VARCHAR(15));